const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('notch', {
  onMetrics: (callback) => ipcRenderer.on('metrics:update', (_event, payload) => callback(payload)),
  onMedia: (callback) => ipcRenderer.on('media:update', (_event, payload) => callback(payload)),
  onControls: (callback) => ipcRenderer.on('controls:update', (_event, payload) => callback(payload)),
  onSettings: (callback) => ipcRenderer.on('settings:update', (_event, payload) => callback(payload)),
  onOverlayMode: (callback) => ipcRenderer.on('overlay:mode', (_event, payload) => callback(payload)),
  onNotification: (callback) => ipcRenderer.on('notifications:update', (_event, payload) => callback(payload)),
  onUpdateStatus: (callback) => ipcRenderer.on('updates:status', (_event, payload) => callback(payload)),
  onScreenVideoShow: (callback) => ipcRenderer.on('screen-video:show-inline', () => callback()),
  onScreenVideoHide: (callback) => ipcRenderer.on('screen-video:hide-inline', () => callback()),
  getMetrics: () => ipcRenderer.invoke('metrics:get'),
  getMedia: () => ipcRenderer.invoke('media:get'),
  getControls: () => ipcRenderer.invoke('controls:get'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  getNotifications: () => ipcRenderer.invoke('notifications:get'),
  dismissNotification: (id) => ipcRenderer.invoke('notifications:dismiss', id),
  getWeather: (city) => ipcRenderer.invoke('weather:get', city),
  clearAppCache: () => ipcRenderer.invoke('app:clear-cache'),
  connectIntegration: (appId, credentials) => ipcRenderer.invoke('integration:connect', appId, credentials),
  disconnectIntegration: (appId) => ipcRenderer.invoke('integration:disconnect', appId),
  getIntegrationStatus: (appId) => ipcRenderer.invoke('integration:status', appId),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  checkForUpdates: (options) => ipcRenderer.invoke('updates:check', options),
  openUpdate: (updateInfo) => ipcRenderer.invoke('updates:open', updateInfo),
  expand: () => ipcRenderer.send('overlay:expand'),
  collapse: () => ipcRenderer.send('overlay:collapse'),
  showSettings: () => ipcRenderer.send('overlay:settings'),
  openSettingsPreferred: () => ipcRenderer.send('settings:open-preferred'),
  showControls: () => ipcRenderer.send('overlay:controls'),
  showMedia: () => ipcRenderer.send('overlay:media'),
  showAlarm: () => ipcRenderer.send('overlay:alarm'),
  closeCurrentWindow: () => ipcRenderer.send('window:close-current'),
  media: (command) => ipcRenderer.invoke('media:command', command),
  quickAction: (action) => ipcRenderer.invoke('quick:action', action),
  showScreenVideo: () => ipcRenderer.invoke('screen-video:show'),
  hideScreenVideo: () => ipcRenderer.invoke('screen-video:hide'),
  toggleScreenVideo: () => ipcRenderer.invoke('screen-video:toggle'),
  getNetworkExtras: (options) => ipcRenderer.invoke('extras:network', options),
  getBrightness: () => ipcRenderer.invoke('brightness:get'),
  setBrightness: (level) => ipcRenderer.invoke('brightness:set', level),
  getRamSnapshot: () => ipcRenderer.invoke('system:ram-snapshot'),
  cleanRam: () => ipcRenderer.invoke('system:clean-ram'),
  getAudioMixer: () => ipcRenderer.invoke('audio-mixer:get'),
  setAudioSessionVolume: (sessionId, volume) => ipcRenderer.invoke('audio-mixer:set-volume', sessionId, volume),
  setAudioSessionMuted: (sessionId, muted) => ipcRenderer.invoke('audio-mixer:set-muted', sessionId, muted),
  openExternalApp: (targetPath) => ipcRenderer.invoke('external-app:open', targetPath),
  listLanguages: () => ipcRenderer.invoke('i18n:list'),
  getLanguage: (code) => ipcRenderer.invoke('i18n:get', code),
  webSearch: (query) => ipcRenderer.invoke('search:web', query)
});
